artifact_location: file:D:/Data Science Projects/customer-churn-prediction/mlflow_runs/565951811302666254
creation_time: 1776524671367
experiment_id: '565951811302666254'
last_update_time: 1776524671367
lifecycle_stage: active
name: MLflow Demo
trace_location: null
workspace: default
