artifact_uri: file:///D:\Data Science Projects\customer-churn-prediction\mlflow_runs/944076202958117275/21808669a6d744c18c5d6d56a2f1db5c/artifacts
end_time: 1776524503733
entry_point_name: ''
experiment_id: '944076202958117275'
lifecycle_stage: active
run_id: 21808669a6d744c18c5d6d56a2f1db5c
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1776524500176
status: 3
tags: []
user_id: Ali Hyder
